import type { Review } from "../../types";

/**
 * Seeded written reviews — a recent sample per product. `product.reviewCount`
 * is the all-time total; the PDP shows these as the most recent ones.
 */
export const mockReviews: Review[] = [
  // Aurora Solitaire Engagement Ring
  {
    id: "r-ring-1",
    productId: "p-ring-sol",
    author: "Ananya S.",
    rating: 5,
    title: "She said yes — and the ring stole the show",
    body: "The six-prong setting holds the stone high and it catches light from across the room. IGI certificate matched the laser inscription exactly. Sized perfectly first time.",
    date: "2026-06-21T09:30:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-ring-2",
    productId: "p-ring-sol",
    author: "Rohan M.",
    rating: 5,
    title: "Better than the mined ring we almost bought",
    body: "We compared this with a mined solitaire at a chain store — same grades, literally half the price. The platinum band has a lovely weight to it.",
    date: "2026-06-08T14:10:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-ring-3",
    productId: "p-ring-sol",
    author: "Priya K.",
    rating: 4,
    title: "Beautiful ring, delivery took a day extra",
    body: "The rose gold is subtle and elegant, not brassy. Four and not five stars only because delivery slipped a day past the estimate — the unboxing made up for it.",
    date: "2026-05-30T18:45:00.000Z",
    verifiedPurchase: true,
  },
  // Celeste Halo Stud Earrings
  {
    id: "r-studs-1",
    productId: "p-studs-halo",
    author: "Meera D.",
    rating: 5,
    title: "Everyday sparkle without trying too hard",
    body: "The halo makes each ear look a full size bigger than the carat suggests. Secure screw backs — I've worn them daily for a month, including workouts.",
    date: "2026-06-18T11:00:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-studs-2",
    productId: "p-studs-halo",
    author: "Kavitha R.",
    rating: 5,
    title: "Anniversary gift, wife loves them",
    body: "Bought the 18k yellow gold pair. Packaging was gorgeous and the certificate cards for both stones were included. Would buy from Green Diamond again.",
    date: "2026-06-02T16:20:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-studs-3",
    productId: "p-studs-halo",
    author: "Ishaan V.",
    rating: 4,
    title: "Great studs, slightly snug butterfly backs",
    body: "Stones are bright white with zero visible inclusions. The backs are a little stiff at first — they loosen up after a week of wear.",
    date: "2026-05-19T08:05:00.000Z",
    verifiedPurchase: false,
  },
  // 1.02ct Round Brilliant
  {
    id: "r-rd-1",
    productId: "p-rd-102",
    author: "Aditi N.",
    rating: 5,
    title: "Ideal cut is not marketing — it's blinding",
    body: "Compared side by side with a friend's mined E/VVS2 and honestly could not tell them apart, except mine cost a third. Hearts-and-arrows visible under the loupe.",
    date: "2026-06-15T10:15:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-rd-2",
    productId: "p-rd-102",
    author: "Farhan A.",
    rating: 5,
    title: "Certificate verified on IGI's site in seconds",
    body: "Report number checked out on igi.org before I even unboxed fully. The stone faces up bigger than 1ct thanks to the ideal proportions.",
    date: "2026-05-28T13:40:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-rd-3",
    productId: "p-rd-102",
    author: "Shreya T.",
    rating: 4,
    title: "Stunning stone, wish there were more photos",
    body: "The diamond itself is flawless to my eye. Product photos could show more angles — the real thing is far more lively than the listing suggests.",
    date: "2026-05-12T19:55:00.000Z",
    verifiedPurchase: true,
  },
  // 1.51ct Oval
  {
    id: "r-ov-1",
    productId: "p-ov-151",
    author: "Nikita J.",
    rating: 5,
    title: "Wears like a 2 carat",
    body: "The elongated shape covers my finger beautifully. Minimal bow-tie effect, which I was worried about with ovals. HPHT growth, no tint I can detect.",
    date: "2026-06-11T12:25:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-ov-2",
    productId: "p-ov-151",
    author: "Arjun P.",
    rating: 4,
    title: "Excellent value for the size",
    body: "F colour is noticeably white even against platinum. Took one star because dispatch took two days — support was responsive about it though.",
    date: "2026-05-25T09:00:00.000Z",
    verifiedPurchase: true,
  },
  // 2.01ct Cushion
  {
    id: "r-cu-1",
    productId: "p-cu-201",
    author: "Devika L.",
    rating: 5,
    title: "Vintage soul, modern fire",
    body: "The crushed-ice sparkle of this cushion is hypnotic. GIA lab-grown report gave us complete confidence for a stone this size.",
    date: "2026-06-09T15:35:00.000Z",
    verifiedPurchase: true,
  },
  // 0.71ct Emerald cut
  {
    id: "r-em-1",
    productId: "p-em-071",
    author: "Sanjay B.",
    rating: 5,
    title: "D/VVS1 step cut — glass-clear",
    body: "Step cuts hide nothing, so the top grades matter. This one is water-clear with crisp, mirrored facets. Perfect for the signet setting we designed.",
    date: "2026-06-14T17:50:00.000Z",
    verifiedPurchase: true,
  },
  // Lumen Tennis Bracelet
  {
    id: "r-brc-1",
    productId: "p-bracelet-tennis",
    author: "Ritu G.",
    rating: 5,
    title: "The double lock is genius",
    body: "Three carats of perfectly matched stones and I don't worry about the clasp — the safety catch has survived two toddlers pulling on it.",
    date: "2026-06-19T20:10:00.000Z",
    verifiedPurchase: true,
  },
  // Solène Solitaire Pendant
  {
    id: "r-pen-1",
    productId: "p-pendant-solitaire",
    author: "Tara W.",
    rating: 5,
    title: "Floats exactly like the name promises",
    body: "The bezel is so fine the stone looks like it's hovering. Chain length is adjustable between two loops, which the listing didn't even mention.",
    date: "2026-06-16T10:45:00.000Z",
    verifiedPurchase: true,
  },
  {
    id: "r-pen-2",
    productId: "p-pendant-solitaire",
    author: "Vikram H.",
    rating: 4,
    title: "Lovely daily-wear piece",
    body: "Gifted for a birthday — she hasn't taken it off. The cable chain is fine but sturdy. Would love a white-gold chain upgrade option.",
    date: "2026-06-01T13:15:00.000Z",
    verifiedPurchase: true,
  },
];
